name: MY Pizza Delivery

on: [push, workflow_dispatch]

jobs:
  Order-Online:
    runs-on: macos-latest

    steps:
      - name: Open Mobile
        run: echo "Opened Mobile"

      - name: Explore Food
        run: echo "I want to eat Pizza"

      - name: Make Payment
        run: echo "Make the payment of \$50"

  Eat-Food:
    runs-on: ubuntu-latest
    needs: Order-Online

    steps:
      - name: Open Mouth
        run: echo "Open Mouth"

      - name: Eat the Food
        run: echo "Eat the Food"